id: "1757254231540"
alias: "[Backup] Alerte si KO 15 min"
description: Notification si le backup reste en KO pendant 15 minutes
triggers:
  - entity_id: sensor.backup_github_status
    to: KO
    for: "00:15:00"
    trigger: state
conditions: []
actions:
  - data:
      title: Backup GitHub
      message: >-
        Échec ou pas de commit depuis 15 min. Vérifie
        /config/.logs/ha_git_backup.log
    action: persistent_notification.create
mode: single