homeassistant:
  # Load packages
  packages: !include_dir_named integrations/
  allowlist_external_dirs:
    - "/config/"

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

script: !include scripts.yaml
scene: !include scenes.yaml

# Pour script python
# python_script: 

# Pour powercalc
powercalc:

# Pour Cloudflared
http:
  use_x_forwarded_for: true

  trusted_proxies:
    - 172.30.0.0/16   # tous les add-ons / ingress / tunnels
    - 192.168.1.0/24  # ton LAN local
  # Protège l’accès à HA
  ip_ban_enabled: true
  # bannissement IP"
  login_attempts_threshold: 3
  # seuil de tentatives
  #clé privé / public
  #ssl_certificate: /ssl/local.crt
  #ssl_key: /ssl/local.key

#renvoi au fichier automations.yaml
automation: !include automations.yaml

#renvoi au fichier répertoire automations/
#automation: !include_dir_merge_list automations/

#renvoi au fichier répertoire template/
template: !include_dir_merge_list templates/

# renvoi au fichier commad_line.yaml
command_line: !include command_line.yaml

#renvoi au fichier camera.yaml -> carte meteo france alerte
camera: !include camera.yaml

#renvoi au fichier utility_meter.yaml
utility_meter: !include utility_meter.yaml

#renvoi au fichier groupe
group: !include group.yaml

#revoin au fuchier input_number.yaml
input_number: !include input_number.yaml

#revoin au fuchier input_boolean.yaml
input_boolean: !include input_boolean.yaml

sensor: !include sensors.yaml

#renvoi au fichier shell_command.yaml
# Services shell_command (NOUVEAU)
shell_command: !include shell_command.yaml

#renvoi au fichier input_text.yaml
input_text: !include input_text.yaml

#renvoi au fichier input_select.yaml
input_select: !include input_select.yaml

# Amazon
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.fr

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids: 
    - !secret id_telegram_HA-Bot

# ==========================================================================
# Zone NOTIFY
# ==========================================================================
notify:
# Telegram
  - platform: telegram
    name: Telegram
    chat_id: !secret id_telegram_HA-Bot

# BASE DE DONNEE MariaDB
recorder:
  db_url: mysql://homeassistant:MariaDB@core-mariadb/homeassistant?charset=utf8mb4
  purge_keep_days: 32
  auto_purge: true
  auto_repack: true
  exclude:
    domains:
      - update
      - persistent_notification
      - sun
      - input_text

    event_types:
      - call_service

    entity_globs:
      - sensor.127_0_0_1*
      - sensor.*linkquality
      - sensor.*last_seen
      - sensor.date*
      - sensor.time*
      - sensor.toshiba*
      - sensor.sandisk*
      - sensor.samsung_ssd_970_evo_plus*
      - sensor.nvidia_nvidia_geforce_rtx_3060*
      - sensor.gigabyte_b450_aorus_elite*
      - sensor.generic_memory*
      - sensor.ethernet*
      - sensor.amd_ryzen_9_5900x*

sql:
  - name: Taille DB Home Assistant
    # Crée sensor.taille_db_home_assistant"
    db_url: mysql://homeassistant:MariaDB@core-mariadb/homeassistant?charset=utf8mb4
    # core-mariadb : URL de la DB de l’add-on MariaDB"
    query: >
      SELECT Round(Sum(data_length + index_length) / POWER(1024,2), 1) AS value
      FROM information_schema.tables
      WHERE table_schema = "homeassistant";
    # Requête 'Database size' (doc officielle MariaDB/MySQL)"
    column: value
    unit_of_measurement: MiB
    device_class: data_size
    unique_id: taille_db_home_assistant

openai_conversation:
  api_key: !secret chat_gpt_api_key
  model: "gpt-4o-mini"

bluetooth:
  device_tracker:
    - platform: bluetooth_le_tracker

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

#smartIR
climate:
  - platform: smartir
    name: Clim Bureau RM4-Mini
    unique_id: clim_bureau_rm4_mini
    device_code: 1108
    controller_data: remote.clim_bureau
    temperature_sensor: sensor.th_bureau_temperature
    humidity_sensor: sensor.th_bureau_humidity

  - platform: smartir
    name: Clim Chambre RM4-Mini
    unique_id: clim_chambre_rm4_mini
    device_code: 1108
    controller_data: remote.clim_chambre
    temperature_sensor: sensor.th_chambre_temperature
    humidity_sensor: sensor.th_chambre_humidity

  - platform: smartir
    name: Clim Salon RM4-Mini
    unique_id: clim_salon_rm4_mini
    device_code: 1082
    controller_data: remote.clim_salon
    temperature_sensor: sensor.th_salon_temperature
    humidity_sensor: sensor.th_salon_humidity