id: "1736451378006"
alias: Chauffage Cuisine Vacances
description: >-
  Allume ou éteint le chauffage selon la température entre 6h00 et 8h30 la
  semaine 
triggers:
  - at: "06:00:00"
    trigger: time
  - entity_id:
      - sensor.th_cuisine_temperature
    below: 19.9
    trigger: numeric_state
  - entity_id:
      - sensor.th_cuisine_temperature
    above: 20.5
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: zone
            entity_id: person.eric
            zone: zone.home
          - condition: time
            after: "06:00:00"
            before: "08:30:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
          - condition: numeric_state
            entity_id: sensor.th_cuisine_temperature
            below: 19.9
        sequence:
          - action: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: heat
            target:
              entity_id: climate.radiateur_cuisine
          - action: notify.alexa_media_echo_dot_cuisine
            metadata: {}
            data:
              message: Le chauffage de la Cuisine est en fonctionnement
          - action: notify.mobile_app_poco_x7_pro
            metadata: {}
            data:
              message: /!\ Chauffage Cuisine "ON" /!\
      - conditions:
          - condition: zone
            entity_id: person.eric
            zone: zone.home
          - condition: time
            after: "06:00:00"
            before: "08:30:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
          - condition: numeric_state
            entity_id: sensor.th_cuisine_temperature
            above: 20.5
        sequence:
          - action: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: "off"
            target:
              entity_id: climate.radiateur_cuisine
          - action: notify.alexa_media_echo_dot_cuisine
            metadata: {}
            data:
              message: Le chauffage de la Cuisine est à l'arrêt
          - action: notify.mobile_app_poco_x7_pro
            metadata: {}
            data:
              message: /!\ Chauffage Cuisine "OFF" /!\
mode: single
