
id: "1737483248264"
alias: Gestion Optimisée du Store Bureau
description: >
  Gère l'ouverture et la fermeture du store du bureau en fonction de la
  température et de l'heure, avec des conditions spécifiques pour le contact de
  la fenêtre et la position du store.
triggers:
  - at: "07:00:00"
    trigger: time
  - event: sunset
    trigger: sun
  - trigger: state
    entity_id:
      - sensor.temperature_cible
  - entity_id: sensor.th_balcon_nord_temperature
    above: 18
    trigger: numeric_state
  - entity_id:
      - sensor.th_balcon_nord_temperature
    above: 25
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: time
            after: "07:00:00"
          - condition: sun
            before: sunset
          - condition: numeric_state
            entity_id: sensor.th_balcon_nord_temperature
            above: 18
            below: 25
          - condition: state
            entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
            state: "off"
          - condition: numeric_state
            entity_id: cover.store_bureau
            attribute: current_position
            below: 50
        sequence:
          - target:
              entity_id: cover.store_bureau
            action: cover.open_cover
            data: {}
        alias: OUVERTURE DU STORE SI APRES 7h & 4 CONDITIONS
      - conditions:
          - condition: numeric_state
            entity_id: sensor.th_balcon_nord_temperature
            above: 24.99
          - condition: state
            entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
            state: "off"
          - condition: numeric_state
            entity_id: cover.store_bureau
            attribute: current_position
            above: 50
        sequence:
          - target:
              entity_id: cover.store_bureau
            action: cover.close_cover
            data: {}
        alias: FERMETURE DU STORE SI T° >25°  & 2 CONDITIONS
      - conditions:
          - condition: sun
            after: sunset
          - condition: state
            entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
            state: "off"
        sequence:
          - target:
              entity_id: cover.store_bureau
            action: cover.close_cover
            data: {}
        alias: FERMETURE DU STORE AU COUCHE DU SOLEIL  & 1 CONDITION
    default: []
mode: single
