esphome:
  name: esp-pression-balcon-n

esp32:
  board: esp32-h2-devkitm-1
  variant: esp32h2
  framework:
    type: esp-idf
    version: recommended

# On utilise cette syntaxe pour bypasser le bug nrf52
# Elle active la radio pour le H2 sans déclencher la dépendance Nordic
esp32_ble_beacon:
  type: iBeacon
  uuid: '12345678-1234-1234-1234-123456789012'

i2c:
  sda: 0
  scl: 1
  scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Température Balcon"
    pressure:
      name: "Pression Balcon"
    address: 0x76

logger:
  level: INFO