alias: (C) Notification température Up ou Down de [6h00 -> 20h00]
description: >
  Notification température Up ou Down en fonction des présences et réseaux
  (6h-20h)
triggers:
  - entity_id:
      - sensor.ne2213_mamour_wi_fi_connection
      - sensor.poco_x7_pro_wi_fi_connection
      - sensor.th_balcon_nord_temperature
    to: null
    trigger: state
conditions:
  - condition: time
    after: "06:00:00"
    before: "20:00:01"
actions:
  - delay: "00:00:02"
  - if:
      - condition: template
        value_template: >
          {{ states('sensor.message_clim_personnalise_6h_20h') in ['unknown',
          'unavailable'] or
             states('sensor.ne2213_mamour_wi_fi_connection') in ['unknown', 'unavailable'] or
             states('sensor.poco_x7_pro_wi_fi_connection') in ['unknown', 'unavailable'] or
             states('sensor.th_balcon_nord_temperature') in ['unknown', 'unavailable'] }}
    then:
      - data:
          message: >-
            ⚠️ Erreur : Un capteur critique est indisponible ! Vérifiez les
            dépendances.
        action: notify.mobile_app_poco_x7_pro
    else:
      - data:
          message: "{{ states('sensor.message_clim_personnalise_6h_20h') }}"
        action: notify.mobile_app_poco_x7_pro
mode: queued
