alias: >-
  (F) [ CLIM ] Automatisation qui détecte quand un climatiseur est désactivé et
  envoie une notification
description: >-
  Automatisation pour détecter quand un climatiseur est désactivé manuellement
  et envoyer une notification, uniquement si toutes les fenêtres sont fermées.
triggers:
  - entity_id:
      - climate.clim_salon_rm4_mini
      - climate.clim_bureau_rm4_mini
      - climate.clim_chambre_rm4_mini
    trigger: state
    from: null
    to: "off"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.entity_id == 'climate.clim_salon_rm4_mini' }}"
              - condition: state
                entity_id: switch.clim_salon_nous
                state: "on"
              - condition: state
                entity_id: switch.clim_du_bureau_nous
                state: "on"
              - condition: state
                entity_id: switch.clim_chambre_nous
                state: "on"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_salon_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_cuisine_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_chambre_ikea_contact
                state: "off"
        sequence:
          - action: notify.mobile_app_poco_x7_pro
            data:
              title: ARRÊT CLIM
              message: La clim. du Salon a été coupée manuellement.
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.entity_id == 'climate.clim_bureau_rm4_mini' }}"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_salon_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_cuisine_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_chambre_ikea_contact
                state: "off"
        sequence:
          - action: notify.mobile_app_poco_x7_pro
            data:
              title: ARRÊT CLIM
              message: La clim. du Bureau a été coupée manuellement.
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.entity_id == 'climate.clim_chambre_rm4_mini' }}"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_salon_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_cuisine_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_bureau_ikea_contact
                state: "off"
              - condition: state
                entity_id: binary_sensor.contact_fenetre_chambre_ikea_contact
                state: "off"
        sequence:
          - action: notify.mobile_app_poco_x7_pro
            data:
              title: ARRÊT CLIM
              message: La clim. de la Chambre a été coupée manuellement.
mode: queued
