alias: (H) [ CLIM DEBUG ] Force clims -> sensor.mode_ete_hiver
description: >
  Vérifie toutes les minutes si les clims sont alignées avec
  'sensor.mode_ete_hiver' et que leurs interrupteurs associés sont allumés. Si
  non, force le mode HVAC à 'sensor.mode_ete_hiver' et notifie uniquement les
  changements.
triggers:
  - minutes: /1
    trigger: time_pattern
  - entity_id:
      - climate.clim_salon_rm4_mini
      - climate.clim_bureau_rm4_mini
      - climate.clim_chambre_rm4_mini
    trigger: state
conditions: []
actions:
  - delay: "00:00:05"
  - variables:
      target_clims: >
        {% set target_clims = [] %} {% if states('climate.clim_salon_rm4_mini')
        != states('sensor.mode_ete_hiver')
              and states('switch.clim_salon_nous') == 'on' %}
          {% set target_clims = target_clims + ['climate.clim_salon_rm4_mini'] %}
        {% endif %} {% if states('climate.clim_bureau_rm4_mini') !=
        states('sensor.mode_ete_hiver')
              and states('switch.clim_du_bureau_nous') == 'on' %}
          {% set target_clims = target_clims + ['climate.clim_bureau_rm4_mini'] %}
        {% endif %} {% if states('climate.clim_chambre_rm4_mini') !=
        states('sensor.mode_ete_hiver')
              and states('switch.clim_chambre_nous') == 'on' %}
          {% set target_clims = target_clims + ['climate.clim_chambre_rm4_mini'] %}
        {% endif %} {{ target_clims }}
      target_clims_names: >
        {% set names = [] %} {% if 'climate.clim_salon_rm4_mini' in target_clims
        %}
          {% set names = names + ['Salon'] %}
        {% endif %} {% if 'climate.clim_bureau_rm4_mini' in target_clims %}
          {% set names = names + ['Bureau'] %}
        {% endif %} {% if 'climate.clim_chambre_rm4_mini' in target_clims %}
          {% set names = names + ['Chambre'] %}
        {% endif %} {{ names | join(', ') }}
  - if:
      - condition: template
        value_template: "{{ target_clims | length > 0 }}"
    then:
      - target:
          entity_id: "{{ target_clims }}"
        data:
          hvac_mode: "{{ states('sensor.mode_ete_hiver') }}"
        action: climate.set_hvac_mode
      - data:
          title: DEBUG CLIM
          message: >
            Force -> {{ states('sensor.mode_ete_hiver') }} pour : {{
            target_clims_names }}
        action: notify.mobile_app_poco_x7_pro
