alias: (L) [DEBUG] Notifier les changements de message clim (Mobile)
description: ""
triggers:
  - entity_id: sensor.message_clim_personnalise_6h_20h
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'CELLULAR' in trigger.to_state.state }}"
        sequence:
          - data:
              message: "[Présence] Personne n'est à la maison (mode CELLULAR/WIFI_?!)"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'MAMOUR' in trigger.to_state.state }}"
        sequence:
          - data:
              message: "[Présence] Seul Mamour est à la maison (Wi-Fi)"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'ERIC' in trigger.to_state.state }}"
        sequence:
          - data:
              message: "[Présence] Seul Eric est à la maison (Wi-Fi)"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Clim [2] en [WIFI]' in trigger.to_state.state }}"
        sequence:
          - data:
              message: "[Présence] Mamour et Eric sont à la maison (Wi-Fi)"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Up >>>' in trigger.to_state.state }}"
        sequence:
          - variables:
              temp_ext: >-
                {{ trigger.to_state.state.split('|')[1].split('Up
                >>>')[1].split('°')[0].strip() }}
          - data:
              message: "[Tendance] Température extérieure en hausse : {{ temp_ext }}°"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Down <<<' in trigger.to_state.state }}"
        sequence:
          - variables:
              temp_ext: >-
                {{ trigger.to_state.state.split('|')[1].split('Down
                <<<')[1].split('°')[0].strip() }}
          - data:
              message: "[Tendance] Température extérieure en baisse : {{ temp_ext }}°"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'stable' in trigger.to_state.state }}"
        sequence:
          - variables:
              temp_ext: >-
                {{
                trigger.to_state.state.split('|')[1].split('°')[0].split('stable
                ')[1].strip() }}
          - data:
              message: "[Tendance] Température extérieure stable : {{ temp_ext }}°"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Heat' in trigger.to_state.state }}"
        sequence:
          - variables:
              message_part: "{{ trigger.to_state.state.split('|')[2] }}"
          - data:
              message: "[Mode] Chauffage activé : {{ message_part }}"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Cool' in trigger.to_state.state }}"
        sequence:
          - variables:
              message_part: "{{ trigger.to_state.state.split('|')[2] }}"
          - data:
              message: "[Mode] Rafraîchissement activé : {{ message_part }}"
            action: notify.mobile_app_poco_x7_pro
      - conditions:
          - condition: template
            value_template: "{{ 'Fan' in trigger.to_state.state }}"
        sequence:
          - data:
              message: "[Mode] Ventilation activée"
            action: notify.mobile_app_poco_x7_pro
