id: "1746383758535"
alias: Update previous humidity
description: Update previous humidity
triggers:
  - minutes: /1
    trigger: time_pattern
conditions: []
actions:
  - data:
      value: "{{ states('sensor.th_balcon_nord_humidity') | float }}"
    target:
      entity_id: input_number.th_balcon_nord_humidity_previous
    action: input_number.set_value
mode: single
