id: "1746383895778"
alias: Update previous temperature
description: Update previous temperature
triggers:
  - minutes: /1
    trigger: time_pattern
conditions: []
actions:
  - data:
      value: "{{ states('sensor.th_balcon_nord_temperature') | float }}"
    target:
      entity_id: input_number.th_balcon_nord_temperature_previous
    action: input_number.set_value
mode: single
