- sensor:
    - name: "Groupe Clim"
      unique_id: groupe_clim
      state: >
        {# Récupérer les valeurs des capteurs #}
        {% set mamour_wifi_ssid = states('sensor.ne2213_mamour_wi_fi_connection') | default('') | string | strip %}
        {% set mamour_net_type = states('sensor.ne2213_mamour_network_type') | default('') | string | strip | lower %}
        {% set eric_wifi_ssid = states('sensor.poco_x7_pro_wi_fi_connection') | default('') | string | strip %}
        {% set eric_net_type = states('sensor.poco_x7_pro_network_type') | default('') | string | strip | lower %}

        {# Définir le SSID du réseau domestique #}
        {% set ssid_home = "Freebox_GG" %}

        {# Déterminer l'état de Mamour et Eric #}
        {% set mamour_wifi_home = mamour_wifi_ssid == ssid_home and mamour_net_type == "wifi" %}
        {% set mamour_wifi_non_home = mamour_wifi_ssid != ssid_home and mamour_net_type == "wifi" %}
        {% set mamour_cell = mamour_net_type == "cellular" %}

        {% set eric_wifi_home = eric_wifi_ssid == ssid_home and eric_net_type == "wifi" %}
        {% set eric_wifi_non_home = eric_wifi_ssid != ssid_home and eric_net_type == "wifi" %}
        {% set eric_cell = eric_net_type == "cellular" %}

        {# Logique pour déterminer le groupe #}
        {% if mamour_cell and eric_cell %}
          groupe_1  {# 2 en cell #}
        {% elif mamour_wifi_non_home and eric_wifi_non_home %}
          groupe_1  {# 2 en wifi_!? #}
        {% elif mamour_wifi_non_home and eric_cell %}
          groupe_1  {# Mamour wifi_!?/cell #}
        {% elif mamour_cell and eric_wifi_non_home %}
          groupe_1  {# Mamour cell/wifi_!? #}
        {% elif eric_wifi_non_home and mamour_cell %}
          groupe_1  {# Eric wifi_!?/cell #}
        {% elif eric_cell and mamour_wifi_non_home %}
          groupe_1  {# Eric cell/wifi_!? #}
        {% elif mamour_wifi_home and eric_wifi_non_home %}
          groupe_2  {# Mamour wifi/!? #}
        {% elif mamour_wifi_home and eric_cell %}
          groupe_2  {# Mamour wifi/cell #}
        {% elif eric_wifi_home and mamour_wifi_non_home %}
          groupe_3  {# Eric wifi/!? #}
        {% elif eric_wifi_home and mamour_cell %}
          groupe_3  {# Eric wifi/cell #}
        {% elif mamour_wifi_home and eric_wifi_home %}
          groupe_4  {# 2 en wifi #}
        {% else %}
          groupe_1  {# Cas par défaut #}
        {% endif %}
