external_components:
  # Le module Zigbee pour H2
  - source: github://luar123/zigbee_esphome
    components: [zigbee]
  # On pointe directement sur le miroir officiel d'ESPHome pour le driver BME280
  - source: 
      type: git
      url: https://github.com/esphome/esphome
      ref: master
    components: [ bme280, i2c ]

esp32:
  board: esp32-h2-devkitm-1
  framework:
    type: esp-idf

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "Température"
      id: "temp_val"
    humidity:
      name: "Humidité"
      id: "hum_val"
    pressure:
      name: "Pression Absolue"
      id: "pres_val"
    update_interval: 60s

# Le reste du code (Zigbee, etc.) reste identique