esphome:
  name: esp-pression-balcon-n
  friendly_name: "Test Hardware SdB"

esp32:
  board: esp32-h2-devkitm-1
  variant: esp32h2
  framework:
    type: esp-idf

# On remplace le Zigbee par le Bluetooth juste pour le test
esp32_ble_beacon:
  type: iBeacon
  uuid: "EDA2408C-3235-46B1-8E8E-3C425AB2352B"

i2c:
  sda: GPIO0
  scl: GPIO1
  scan: true  # TRÈS IMPORTANT : va lister les composants trouvés

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Température Test"
    pressure:
      name: "Pression Test"
    address: 0x76
    update_interval: 10s