id: "1752138633943"
alias: (G) [CLIM ] Notification de changement de mode Été/Fan/Hiver
description: >-
  Notification lorsque le mode change entre Été, Ventilateur ou Hiver (cool /
  fan_only / heat)
triggers:
  - entity_id: sensor.mode_ete_hiver
    trigger: state
conditions: []
actions:
  - delay: "00:00:03"
  - data:
      message: "Le mode a changé pour: {{ states('sensor.mode_ete_hiver_etat') }}"
      title: CHANGEMENT DE MODE
    action: notify.mobile_app_poco_x7_pro
mode: single
